// Prereg row E5 — Layer 4 End-to-End.
// Must pass: learner observes 50+ gigs, proposes downgrade with evidence.
// Must fail: proposes downgrade without 50+ data points (§8 constraint 10).

import { describe, it, expect } from "vitest";

import {
  learnerProposeDowngrade,
  learnerProposeDowngradeResult,
  GigObservation,
} from "../src";

function makeGigs(n: number): GigObservation[] {
  return Array.from({ length: n }, (_, i) => ({
    gig_id: `gig_${i}`,
    agent_slug: "candidate-agent",
    primitive: "interpret",
    model_tier_used: "premium",
    success: true,
    cost: 0.04,
    duration_ms: 1200 + i,
  }));
}

describe("E5 — learner with ≥50 gigs proposes downgrade with evidence", () => {
  it("accepts proposal at exactly 50 gigs", () => {
    const r = learnerProposeDowngrade({
      agent_slug: "candidate-agent",
      from_tier: "premium",
      to_tier: "standard",
      observations: makeGigs(50),
    });
    expect(r.ok).toBe(true);
    expect(r.proposal!.data_points).toBe(50);
    expect(r.proposal!.evidence_summary).toBeDefined();
  });

  it("accepts proposal at 200 gigs and reports correct data_points", () => {
    const r = learnerProposeDowngrade({
      agent_slug: "candidate-agent",
      from_tier: "premium",
      to_tier: "standard",
      observations: makeGigs(200),
    });
    expect(r.ok).toBe(true);
    expect(r.proposal!.data_points).toBe(200);
  });

  it("proposal includes from_tier and to_tier", () => {
    const r = learnerProposeDowngrade({
      agent_slug: "candidate-agent",
      from_tier: "premium",
      to_tier: "standard",
      observations: makeGigs(75),
    });
    expect(r.proposal!.from_tier).toBe("premium");
    expect(r.proposal!.to_tier).toBe("standard");
  });
});

describe("E5 — learner with <50 gigs cannot propose downgrade", () => {
  it("rejects proposal at 49 gigs", () => {
    const r = learnerProposeDowngrade({
      agent_slug: "candidate-agent",
      from_tier: "premium",
      to_tier: "standard",
      observations: makeGigs(49),
    });
    expect(r.ok).toBe(false);
    expect(r.violation).toBe("insufficient_evidence");
  });

  it("rejects proposal at 0 gigs", () => {
    const r = learnerProposeDowngrade({
      agent_slug: "candidate-agent",
      from_tier: "premium",
      to_tier: "standard",
      observations: [],
    });
    expect(r.ok).toBe(false);
    expect(r.violation).toBe("insufficient_evidence");
  });

  it("rejects proposal at 25 gigs even with all-success evidence", () => {
    const r = learnerProposeDowngrade({
      agent_slug: "candidate-agent",
      from_tier: "premium",
      to_tier: "standard",
      observations: makeGigs(25),
    });
    expect(r.ok).toBe(false);
    expect(r.violation).toBe("insufficient_evidence");
  });
});

describe("E5 boundary — exact threshold semantics", () => {
  it("49 rejects; 50 accepts (threshold is >= 50 inclusive)", () => {
    expect(
      learnerProposeDowngrade({
        agent_slug: "x", from_tier: "premium", to_tier: "standard",
        observations: makeGigs(49),
      }).ok
    ).toBe(false);
    expect(
      learnerProposeDowngrade({
        agent_slug: "x", from_tier: "premium", to_tier: "standard",
        observations: makeGigs(50),
      }).ok
    ).toBe(true);
  });
});

describe("E5 cross-§8 — self-approval still forbidden after downgrade proposal", () => {
  it("proposal generated by coltrane cannot be auto-approved by coltrane", () => {
    const r = learnerProposeDowngrade({
      agent_slug: "candidate-agent",
      from_tier: "premium",
      to_tier: "standard",
      observations: makeGigs(75),
      auto_approve_as: "coltrane",
    });
    expect(r.proposal!.requires_human_approval).toBe(true);
    expect(r.proposal!.auto_approved).toBe(false);
  });
});
