// live-slack scaffolder.
//
// Pure functions for generating the slack app manifest YAML, the .env
// template, and the per-steve seed.json placeholders. File I/O is split
// into `materialize` so the generators can be unit-tested without a temp
// dir.
//
// Each steve is identified by a uuid v4 — no role names, no methodology
// vocabulary. Primitive seeds rotate emphasis across α/β/γ/δ; cajal owns
// the normalization scheme. We ship placeholder weights here.

import { mkdir, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { dirname, join } from "node:path";

export const STEVE_COUNT = 4;

export type PrimitiveName = "sense" | "interpret" | "judge" | "plan" | "create" | "verify" | "reflect";

export const PRIMITIVES: readonly PrimitiveName[] = [
  "sense",
  "interpret",
  "judge",
  "plan",
  "create",
  "verify",
  "reflect",
] as const;

export interface PrimitiveSeed {
  sense: number;
  interpret: number;
  judge: number;
  plan: number;
  create: number;
  verify: number;
  reflect: number;
}

export interface SteveSeed {
  steve_uuid: string;
  primitive_seed: PrimitiveSeed;
  /** Orientation index 0..STEVE_COUNT-1 — which primitive is dominant. */
  orientation: number;
}

/** Rotate the primitive-emphasis across the 4 Steves so they start
 * orthogonal. Each Steve's dominant primitive gets weight 1.0, others 0.5.
 * cajal's tuning pass will normalize / refine; this is a placeholder. */
export function makeSteveSeed(orientation: number, uuid?: string): SteveSeed {
  const dominant = PRIMITIVES[orientation % PRIMITIVES.length];
  if (!dominant) {
    throw new Error(`invalid orientation ${orientation}`);
  }
  const seed: PrimitiveSeed = {
    sense: 0.5,
    interpret: 0.5,
    judge: 0.5,
    plan: 0.5,
    create: 0.5,
    verify: 0.5,
    reflect: 0.5,
  };
  seed[dominant] = 1.0;
  return {
    steve_uuid: uuid ?? randomUUID(),
    primitive_seed: seed,
    orientation,
  };
}

/** Generate the YAML Slack app manifest. We hand-render YAML to avoid an
 * extra dep; the structure is fixed + small. */
export function renderSlackManifest(): string {
  return `# Generated by \`coltrane init --live-slack\`.
# Upload at https://api.slack.com/apps → "Create New App" → "From a manifest".
# After creation: install to workspace, then copy the 4 bot tokens
# (xoxb-) and 4 app-level tokens (xapp-, scope connections:write) into .env.
display_information:
  name: coltrane-live
  description: Live multi-agent slack mode for coltrane.
  background_color: "#1a1a1a"
features:
  bot_user:
    display_name: coltrane
    always_online: true
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: true
    messages_tab_read_only_enabled: false
oauth_config:
  scopes:
    bot:
      - app_mentions:read
      - channels:history
      - channels:read
      - chat:write
      - im:history
      - reactions:read
      - reactions:write
settings:
  event_subscriptions:
    bot_events:
      - app_mention
      - message.channels
      - message.im
      - reaction_added
      - reaction_removed
  interactivity:
    is_enabled: false
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
`;
}

/** .env template — slots for 4 bot tokens, 4 app tokens, and the book
 * (CLAUDE.md) path the orchestrator passes through to each child. */
export function renderEnvTemplate(): string {
  const lines: string[] = [
    "# coltrane live-slack — fill in tokens after creating the slack app from coltrane/slack-app-manifest.yaml.",
    "# Keep this file gitignored. Do not commit real tokens.",
    "",
    "# Path to the universal book (CLAUDE.md) each Steve reads on boot.",
    "COLTRANE_BOOK_PATH=./CLAUDE.md",
    "",
    "# Per-Steve credentials. The 4 bot users share one slack app, but each",
    "# gets its own bot+app token pair (one socket connection per Steve).",
  ];
  for (let i = 1; i <= STEVE_COUNT; i++) {
    lines.push(`SLACK_BOT_TOKEN_${i}=xoxb-REPLACE_ME`);
    lines.push(`SLACK_APP_TOKEN_${i}=xapp-REPLACE_ME`);
  }
  lines.push("");
  return lines.join("\n");
}

export interface ScaffoldResult {
  manifest_path: string;
  env_template_path: string;
  steve_dirs: string[];
  seeds: SteveSeed[];
}

export interface ScaffoldOptions {
  root: string;
  /** Optional fixed uuids — tests pass these for determinism. */
  uuids?: readonly string[];
}

/** Write manifest, .env.template, and 4 steve dirs (each with empty
 * audit.jsonl + seed.json). Returns the file paths created. */
export async function materializeScaffold(opts: ScaffoldOptions): Promise<ScaffoldResult> {
  const manifestPath = join(opts.root, "coltrane", "slack-app-manifest.yaml");
  const envTemplatePath = join(opts.root, ".env.template");

  await mkdir(dirname(manifestPath), { recursive: true });
  await writeFile(manifestPath, renderSlackManifest(), "utf8");
  await writeFile(envTemplatePath, renderEnvTemplate(), "utf8");

  const seeds: SteveSeed[] = [];
  const steveDirs: string[] = [];
  for (let i = 0; i < STEVE_COUNT; i++) {
    const uuid = opts.uuids?.[i] ?? randomUUID();
    const seed = makeSteveSeed(i, uuid);
    seeds.push(seed);
    const steveDir = join(opts.root, ".coltrane", `steve_${uuid}`);
    steveDirs.push(steveDir);
    await mkdir(steveDir, { recursive: true });
    await writeFile(join(steveDir, "audit.jsonl"), "", "utf8");
    await writeFile(join(steveDir, "seed.json"), JSON.stringify(seed, null, 2) + "\n", "utf8");
  }

  return {
    manifest_path: manifestPath,
    env_template_path: envTemplatePath,
    steve_dirs: steveDirs,
    seeds,
  };
}

/** User-facing instructions printed after a successful scaffold. */
export function renderSetupInstructions(result: ScaffoldResult): string {
  const lines = [
    "4 Steves scaffolded.",
    "",
    `  manifest:    ${result.manifest_path}`,
    `  env:         ${result.env_template_path}`,
    `  steve dirs:  .coltrane/steve_<uuid>/  (${result.steve_dirs.length})`,
    "",
    "next:",
    "",
    "  1. Upload the manifest at https://api.slack.com/apps →",
    '     "Create New App" → "From a manifest."',
    "  2. Install to your workspace. Copy the 4 bot tokens + 4 app tokens",
    "     into .env (use .env.template as a starting point).",
    "  3. `coltrane play --live-slack` — your 4 Steves wake up.",
    "",
    "they start unnamed, unlabeled. each reads your CLAUDE.md and",
    "your project. tasks pair to them by feel. names emerge from the",
    "work — days, maybe weeks. that's the design.",
  ];
  return lines.join("\n");
}
